version: '2'
services:
    bugtracker-app:
        image: bugtracker
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://bugtracker-postgresql:5432/BugTracker
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    bugtracker-postgresql:
        extends:
            file: postgresql.yml
            service: bugtracker-postgresql
